### ISSUE TITLE
Add option to generate collection specific CMD/ENTRYPOINT

### ISSUE THREAD

**Issue by humaton** [sclorg/rhscl2dockerfile#4]
Some collections require special command to be run at start time of container (postgre/mysql).
Enable option in yaml file to assign script to run with container startup.

**Comment by hhorak** [comment]
Thinking loudly about implementation... We also need to have some convention where to store these scripts (entrypoint scripts). since we may end up with different scripts for different versions of stacks, I'd suggest the following structure:
stackfamily/version/entrypointscript.sh
e.g.:

    mysql/5.5/run-mysql.sh
    mysql/5.5/helper.sh
    mysql/5.6/run-mysql.sh
    mariadb/5.5/run-mysql.sh
    mariadb/10.0/run-mysql.sh

(this is actually a bit similar to what openshift uses at https://github.com/openshift/mysql)

After generation the scripts would be located at:

    rhel7.mysql55/run-mysql.sh
    rhel7.mysql55/helper.sh

Now, since because of systemd-container and other RHEL-version specific features, we may want to use different scripts for 6 and 7, we will probably need rhel-version specific keys in the yaml configuration, so what we may have in the yaml is:

    rh-mysql56:
      install: rh-mysql56
      expose: [3306]
      entrypoint.rhel6: mysql/5.5/rhel6.run-mysql.sh
      entrypoint.rhel7: mysql/5.5/rhel7.run-mysql.sh

but when using just 'entrypoint' key, it would use the same path for all versions:

      entrypoint: mysql/5.5/run-mysql.sh

(this may be needed in case of other keys at some point as well (e.g. installing additional packages))

**Comment by hhorak** [comment]
It also seems we should separate ENTRYPOINT/CMD commands called in the dockerfile and adding scripts including for those calls. So the config could actually look like:

    rh-mysql56:
      install: rh-mysql56
      expose: [3306]
      entrypoint: run-mysql.sh
      cmd: mysqld
      include.rhel6: mysql/5.5/rhel6.run-mysql.sh run-mysql.sh /usr/local/bin/
      include.rhel7: mysql/5.5/rhel7.run-mysql.sh run-mysql.sh /usr/local/bin/

which would add the following line into the dockerfile:

    ADD rhel7.mysql55/run-mysql.sh /usr/local/bin/run-mysql.sh
    ENTRYPOINT [ "run-mysql.sh" ]
    CMD [ "mysqld" ]

**Comment by hhorak** [comment]
Commit 25e0002b09 adds this feature.
